spring:
  application:
    name: stockflow

  datasource:
    url: jdbc:postgresql://localhost:5432/stockflow
    username: stockflow_user
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  integrations:
    cnpja:
      base-url: https://open.cnpja.com
    s3:
      endpoint: http://localhost:4566
      region: us-east-1
      bucket: stockflow-produtos
      access-key: test
      secret-key: test
      path-style-access: true
      auto-create-bucket: true
      public-base-url: http://localhost:4566
