spring:
  application:
    name: stockflow

  datasource:
    url: jdbc:postgresql://localhost:5432/stockflow
    username: stockflow_user
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  integrations:
    cnpja:
      base-url: https://open.cnpja.com